export const userActionTypes = {
    SIGN_UP_STUDENT_START: "SIGN_UP_STUDENT_START",
    SIGN_UP_STUDENT_SUCCESS: "SIGN_UP_STUDENT_SUCCESS",
    SIGN_UP_STUDENT_FAILURE: "SIGN_UP_STUDENT_FAILURE",
    SIGN_IN_STUDENT_START: "SIGN_IN_STUDENT_START",
    SIGN_IN_STUDENT_SUCCESS: "SIGN_IN_STUDENT_SUCCESS",
    SIGN_IN_STUDENT_FAILURE: "SIGN_IN_STUDENT_FAILURE",
   
}