const userActionTypes = {
  SIGN_UP_USER_START: 'SIGN_UP_USER_START',
  SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
  SIGN_UP_USER_FAILURE: 'SIGN_UP_USER_FAILURE',
  SIGN_IN_USER_START: 'SIGN_IN_USER_START',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  TOGGLE_PROFILE_HIDDEN: 'TOGGLE_PROFILE_HIDDEN',
  GET_COURSE_SUBSCRIPTIONS_START: 'GET_COURSE_SUBSCRIPTIONS_START',
  GET_COURSE_SUBSCRIPTIONS_SUCCESS: 'GET_COURSE_SUBSCRIPTIONS_SUCCESS',
  GET_COURSE_SUBSCRIPTIONS_FAILURE: 'GET_COURSE_SUBSCRIPTIONS_FAILURE'
};

export default userActionTypes;
